<?php
declare(strict_types=1);
require __DIR__ . '/app/bootstrap.php';require_once __DIR__ . '/app/Badge.php';Auth::requireLogin();$pdo=Database::connection();ensure_member_soft_delete_schema($pdo);ensure_badge_schema($pdo);$id=(int)($_GET['id']??0);$mode=(string)($_GET['mode']??'view');
try{$member=badge_member_data($pdo,$id);$template=badge_pick_template($pdo,$member);if(!$template)throw new RuntimeException('Er is nog geen actieve algemene of taggebonden lidkaart-template ingesteld.');$layout=badge_layout($template);}catch(Throwable $e){http_response_code(404);exit('Lidkaart kan niet worden gemaakt: '.e($e->getMessage()));}
$data=['full_name'=>$member['full_name'],'first_name'=>$member['first_name'],'last_name'=>$member['last_name'],'member_number'=>$member['member_number']??'','photo'=>$member['photo_path']??'','member_type'=>$member['member_type_label'],'status'=>$member['status_label'],'member_since'=>$member['member_since']??'','birth_date'=>$member['birth_date']??'','email'=>$member['email']??'','mobile'=>$member['mobile']??'','address'=>$member['address']??'','postal_city'=>$member['postal_city'],'weight_kg'=>($member['weight_kg']??'')!==''?((string)$member['weight_kg'].' kg'):'','tags'=>$member['tags'],'payment_status'=>$member['payment_status_label'],'free_flight_entitled'=>$member['free_flight_entitled_label'],'free_flight_date'=>$member['free_flight_date']??''];
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lidkaart <?=e($member['full_name'])?></title><style>*{box-sizing:border-box}body{font-family:Arial,sans-serif;margin:0;background:#e8ebef}.toolbar{display:flex;justify-content:center;gap:10px;padding:14px}.btn{padding:10px 14px;border:0;border-radius:9px;background:#111;color:#fff;text-decoration:none;cursor:pointer;font-weight:700}.secondary{background:#fff;color:#111}.wrap{display:flex;justify-content:center;padding:18px}.badge{position:relative;width:86mm;height:54mm;background:#fff;overflow:hidden;box-shadow:0 8px 28px #0004}.badge #bg{position:absolute;inset:0;width:100%;height:100%}.field{position:absolute;display:flex;align-items:center;overflow:hidden;line-height:1.05;white-space:nowrap}.code{padding:0!important}.qrbox>div,.qrbox canvas,.qrbox img{width:100%!important;height:100%!important;display:block!important}.barcode svg{width:100%;height:100%;display:block}.photoField{justify-content:center;align-items:center}.photoField img{width:100%;height:100%;object-fit:contain;object-position:center;display:block}@page{size:86mm 54mm;margin:0}@media print{html,body{width:86mm;height:54mm;background:#fff}.toolbar{display:none}.wrap{padding:0}.badge{box-shadow:none}}</style></head><body><div class="toolbar"><button class="btn" id="printBtn">Print lidkaart</button><button class="btn" id="downloadBtn">Download Badge PDF</button><a class="btn secondary" href="/member.php?id=<?=$id?>">← Lidfiche</a></div><div class="wrap"><div class="badge" id="badge"><canvas id="bg"></canvas></div></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script><script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.6/dist/JsBarcode.all.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script><script type="module">
import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const pdfUrl=<?=json_encode($template['pdf_path'],JSON_UNESCAPED_SLASHES)?>,layout=<?=json_encode($layout,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,data=<?=json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,memberNumber=<?=json_encode((string)($member['member_number']??''))?>,mode=<?=json_encode($mode)?>,badge=document.getElementById('badge'),bg=document.getElementById('bg'),ctx=bg.getContext('2d');
function fmtDate(v){if(!v)return'';const p=String(v).split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:v}function value(f){return['member_since','birth_date','free_flight_date'].includes(f)?fmtDate(data[f]||''):(data[f]??'')}
async function drawPdf(){const pdf=await pdfjsLib.getDocument(pdfUrl).promise,page=await pdf.getPage(1),base=page.getViewport({scale:1}),vp=page.getViewport({scale:1600/base.width});bg.width=1600;bg.height=Math.round(vp.height);await page.render({canvasContext:ctx,viewport:vp}).promise}
function renderFields(){badge.querySelectorAll('.field').forEach(n=>n.remove());for(const it of layout){const d=document.createElement('div'),f=it.field||'';d.className='field'+(f==='photo'?' photoField':'')+(f==='qr_member_number'?' code qrbox':'')+(f==='barcode_member_number'?' code barcode':'');Object.assign(d.style,{left:(it.x/86*100)+'%',top:(it.y/54*100)+'%',width:(it.w/86*100)+'%',height:(it.h/54*100)+'%',fontFamily:it.font||'Arial',fontSize:(it.size||12)+'pt',color:it.color||'#111',fontWeight:it.bold?'700':'400',justifyContent:it.align==='center'?'center':it.align==='right'?'flex-end':'flex-start',textAlign:it.align||'left'});badge.appendChild(d);
 if(it.type==='text'){d.textContent=it.text||''}else if(f==='qr_member_number'){const q=document.createElement('div');q.style.cssText='width:100%;height:100%';d.appendChild(q);const px=Math.max(64,Math.round(Math.min(d.getBoundingClientRect().width,d.getBoundingClientRect().height)*4));new QRCode(q,{text:memberNumber,width:px,height:px,correctLevel:QRCode.CorrectLevel.M});const generated=q.querySelector('canvas,img');if(generated){generated.style.width='100%';generated.style.height='100%'}}else if(f==='barcode_member_number'){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');d.appendChild(svg);JsBarcode(svg,memberNumber,{format:'CODE128',displayValue:false,margin:0,height:100,width:2})}else if(f==='photo'){if(data.photo){const img=document.createElement('img');img.src=data.photo;d.appendChild(img)}}else d.textContent=value(f)}}
async function waitImages(){await Promise.all([...badge.querySelectorAll('img')].map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=img.onerror=r})));await new Promise(r=>setTimeout(r,100))}
async function downloadPdf(){try{await waitImages();const c=await html2canvas(badge,{scale:5,useCORS:true,allowTaint:false,backgroundColor:'#fff',logging:false});const jspdf=window.jspdf;if(!jspdf||!jspdf.jsPDF)throw new Error('PDF-module kon niet worden geladen.');const pdf=new jspdf.jsPDF({orientation:'landscape',unit:'mm',format:[86,54],compress:true});pdf.addImage(c.toDataURL('image/jpeg',0.98),'JPEG',0,0,86,54,undefined,'FAST');pdf.save('lidkaart-'+(memberNumber||'lid')+'.pdf')}catch(err){console.error(err);alert('Download van de badge-PDF is mislukt. Vernieuw de pagina en probeer opnieuw.')}}
async function ready(){await drawPdf();renderFields();await waitImages();if(mode==='print')setTimeout(()=>window.print(),200);if(mode==='download')setTimeout(downloadPdf,200)}printBtn.onclick=()=>window.print();downloadBtn.onclick=downloadPdf;await ready();
</script></body></html>