<?php
declare(strict_types=1);
require __DIR__ . '/app/bootstrap.php';
require_once __DIR__ . '/app/Badge.php';
Auth::requireLogin();
$pdo=Database::connection();ensure_badge_schema($pdo);
$id=(int)($_GET['id']??$_POST['id']??0);$message='';$error='';
$stmt=$pdo->prepare('SELECT bt.*,t.name tag_name FROM badge_templates bt LEFT JOIN tags t ON t.id=bt.tag_id WHERE bt.id=:id');$stmt->execute(['id'=>$id]);$template=$stmt->fetch();if(!$template){http_response_code(404);exit('Template niet gevonden.');}
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf();
    try{$raw=(string)($_POST['layout_json']??'[]');$layout=json_decode($raw,true);if(!is_array($layout))throw new RuntimeException('Ongeldige layout.');if(count($layout)>50)throw new RuntimeException('Maximaal 50 elementen per lidkaart.');
        $allowed=array_keys(badge_field_catalog());$clean=[];foreach($layout as$item){if(!is_array($item)||!in_array($item['field']??'',$allowed,true))continue;$clean[]=['type'=>'field','field'=>(string)$item['field'],'x'=>max(0,min(86,(float)($item['x']??0))),'y'=>max(0,min(54,(float)($item['y']??0))),'w'=>max(3,min(86,(float)($item['w']??30))),'h'=>max(3,min(54,(float)($item['h']??7))),'font'=>in_array($item['font']??'Arial',['Arial','Helvetica','Verdana','Georgia','Times New Roman','Courier New'],true)?(string)$item['font']:'Arial','size'=>max(5,min(48,(float)($item['size']??12))),'color'=>preg_match('/^#[0-9a-fA-F]{6}$/',(string)($item['color']??''))?(string)$item['color']:'#111111','bold'=>!empty($item['bold']),'align'=>in_array($item['align']??'left',['left','center','right'],true)?(string)$item['align']:'left'];}
        $json=json_encode($clean,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$pdo->prepare('UPDATE badge_templates SET layout_json=:j WHERE id=:id')->execute(['j'=>$json,'id'=>$id]);$template['layout_json']=$json;$message='Ontwerp opgeslagen.';
    }catch(Throwable $e){$error=$e->getMessage();}
}
$catalog=badge_field_catalog();$layout=badge_layout($template);
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lidkaart ontwerpen - Heli One</title><style>
body{font-family:Arial,sans-serif;background:#f5f6f8;margin:0;color:#171717}header{background:#111;color:#fff;padding:18px 28px;display:flex;justify-content:space-between}header a{color:#fff}main{max-width:1500px;margin:24px auto;padding:0 20px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.btn{display:inline-block;padding:10px 14px;border:0;border-radius:9px;background:#111;color:#fff;text-decoration:none;cursor:pointer;font-weight:700}.secondary{background:#e7eaee;color:#111}.ok,.err{padding:12px 14px;border-radius:9px}.ok{background:#e9f8ee}.err{background:#feecec}.muted{color:#69707a}.workspace{display:grid;grid-template-columns:250px minmax(600px,1fr) 280px;gap:18px;margin-top:18px;align-items:start}.panel{background:#fff;border-radius:14px;padding:16px;box-shadow:0 4px 18px #0000000d}.palette{display:grid;gap:7px}.fieldbtn{padding:9px;border:1px solid #d9dde2;border-radius:8px;background:#fff;text-align:left;cursor:pointer}.stagewrap{background:#dfe3e8;border-radius:14px;padding:24px;overflow:auto}.stage{position:relative;width:860px;height:540px;background:#fff;box-shadow:0 8px 28px #0003;overflow:hidden;transform-origin:top left}.stage canvas{position:absolute;inset:0;width:100%;height:100%}.item{position:absolute;box-sizing:border-box;border:1px dashed transparent;cursor:move;display:flex;align-items:center;overflow:hidden;line-height:1.05;user-select:none;padding:1px 2px;white-space:nowrap}.item:hover,.item.selected{border-color:#1473e6;background:#1473e611}.item.code{justify-content:center;background:#fff8}.controls label{display:block;font-size:12px;font-weight:700;margin:10px 0 4px}.controls input,.controls select{width:100%;box-sizing:border-box;padding:8px;border:1px solid #d6dbe1;border-radius:7px}.row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.check{display:flex;align-items:center;gap:7px;margin-top:10px}.check input{width:auto}.danger{background:#8f1d1d}.savebar{margin-top:16px;display:flex;gap:10px;justify-content:flex-end}@media(max-width:1100px){.workspace{grid-template-columns:1fr}.stagewrap{order:1}.panel{order:2}}</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs" type="module"></script></head><body><header><strong>Heli One Members</strong><div><a href="/badge-templates.php">Templates</a> · <a href="/">Dashboard</a></div></header><main><div class="top"><div><h1><?=e($template['name'])?></h1><div class="muted"><?= $template['tag_id']===null?'ALGEMEEN':'Tag: '.e($template['tag_name']) ?> · 86 × 54 mm</div></div><a class="btn secondary" href="/badge-templates.php">← Templates</a></div><?php if($message):?><p class="ok"><?=e($message)?></p><?php endif;?><?php if($error):?><p class="err"><?=e($error)?></p><?php endif;?><form method="post" id="saveForm"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="layout_json" id="layout_json"><div class="workspace"><aside class="panel"><h3>Velden toevoegen</h3><div class="palette"><?php foreach($catalog as$key=>$label):?><button type="button" class="fieldbtn" data-field="<?=e($key)?>"><?=e($label)?></button><?php endforeach;?></div><p class="muted" style="font-size:12px">Klik een veld aan en versleep het daarna op de kaart.</p></aside><section class="stagewrap"><div class="stage" id="stage"><canvas id="bg"></canvas></div></section><aside class="panel controls"><h3>Element</h3><div id="noSelection" class="muted">Selecteer een element op de kaart.</div><div id="editor" hidden><label>Veld</label><input id="cField" disabled><div class="row"><div><label>X (mm)</label><input id="cX" type="number" step="0.1"></div><div><label>Y (mm)</label><input id="cY" type="number" step="0.1"></div></div><div class="row"><div><label>Breedte (mm)</label><input id="cW" type="number" step="0.1"></div><div><label>Hoogte (mm)</label><input id="cH" type="number" step="0.1"></div></div><label>Lettertype</label><select id="cFont"><option>Arial</option><option>Helvetica</option><option>Verdana</option><option>Georgia</option><option>Times New Roman</option><option>Courier New</option></select><div class="row"><div><label>Grootte (pt)</label><input id="cSize" type="number" min="5" max="48" step="0.5"></div><div><label>Kleur</label><input id="cColor" type="color"></div></div><label>Uitlijning</label><select id="cAlign"><option value="left">Links</option><option value="center">Midden</option><option value="right">Rechts</option></select><label class="check"><input id="cBold" type="checkbox"> Vet</label><button type="button" id="remove" class="btn danger" style="margin-top:14px">Element verwijderen</button></div></aside></div><div class="savebar"><button class="btn" type="submit">Ontwerp opslaan</button></div></form></main><script type="module">
import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const pdfUrl=<?=json_encode($template['pdf_path'],JSON_UNESCAPED_SLASHES)?>;const stage=document.getElementById('stage'),canvas=document.getElementById('bg'),ctx=canvas.getContext('2d');
const labels=<?=json_encode($catalog,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;let items=<?=json_encode($layout,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>;let selected=-1;
async function drawPdf(){const pdf=await pdfjsLib.getDocument(pdfUrl).promise;const page=await pdf.getPage(1);const v=page.getViewport({scale:1});const scale=1200/v.width;const vp=page.getViewport({scale});canvas.width=1200;canvas.height=Math.round(vp.height);await page.render({canvasContext:ctx,viewport:vp}).promise;}
function sample(field){if(field==='full_name')return 'Jan Peeters';if(field==='member_number')return 'HO-000123';if(field==='member_type')return 'Vliegend';if(field==='status')return 'Actief';if(field==='member_since')return '01/01/2025';if(field==='qr_member_number')return '▦ QR HO-000123';if(field==='barcode_member_number')return '▥ ||| || ||||';return labels[field]||field;}
function mmx(v){return v/86*860}function mmy(v){return v/54*540}function pxToMmX(v){return v/860*86}function pxToMmY(v){return v/540*54}
function render(){stage.querySelectorAll('.item').forEach(n=>n.remove());items.forEach((it,i)=>{const d=document.createElement('div');d.className='item'+(i===selected?' selected':'')+((it.field||'').includes('qr_')||(it.field||'').includes('barcode_')?' code':'');d.dataset.i=i;d.textContent=sample(it.field);Object.assign(d.style,{left:mmx(it.x)+'px',top:mmy(it.y)+'px',width:mmx(it.w)+'px',height:mmy(it.h)+'px',fontFamily:it.font||'Arial',fontSize:(it.size||12)*1.65+'px',color:it.color||'#111',fontWeight:it.bold?'700':'400',justifyContent:it.align==='center'?'center':it.align==='right'?'flex-end':'flex-start',textAlign:it.align||'left'});d.addEventListener('pointerdown',startDrag);d.addEventListener('click',()=>select(i));stage.appendChild(d);});syncEditor();}
function select(i){selected=i;render()}
function startDrag(e){e.preventDefault();const i=+e.currentTarget.dataset.i;selected=i;const it=items[i],sx=e.clientX,sy=e.clientY,ox=it.x,oy=it.y;const move=ev=>{it.x=Math.max(0,Math.min(86-it.w,ox+pxToMmX(ev.clientX-sx)));it.y=Math.max(0,Math.min(54-it.h,oy+pxToMmY(ev.clientY-sy)));render()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
document.querySelectorAll('.fieldbtn').forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.field;const code=f.includes('qr_')||f.includes('barcode_');items.push({type:'field',field:f,x:5,y:5,w:code?22:40,h:code?18:7,font:'Arial',size:code?9:12,color:'#111111',bold:false,align:'left'});selected=items.length-1;render()}));
const ids=['cX','cY','cW','cH','cFont','cSize','cColor','cAlign','cBold'];function syncEditor(){const ed=document.getElementById('editor'),no=document.getElementById('noSelection');if(selected<0||!items[selected]){ed.hidden=true;no.hidden=false;return}ed.hidden=false;no.hidden=true;const it=items[selected];cField.value=labels[it.field]||it.field;cX.value=it.x.toFixed(1);cY.value=it.y.toFixed(1);cW.value=it.w.toFixed(1);cH.value=it.h.toFixed(1);cFont.value=it.font;cSize.value=it.size;cColor.value=it.color;cAlign.value=it.align;cBold.checked=!!it.bold}
function apply(){if(selected<0)return;const it=items[selected];it.x=+cX.value||0;it.y=+cY.value||0;it.w=Math.max(3,+cW.value||3);it.h=Math.max(3,+cH.value||3);it.font=cFont.value;it.size=+cSize.value||12;it.color=cColor.value;it.align=cAlign.value;it.bold=cBold.checked;render()}
ids.forEach(id=>document.getElementById(id).addEventListener(id==='cBold'?'change':'input',apply));document.getElementById('remove').addEventListener('click',()=>{if(selected<0)return;items.splice(selected,1);selected=-1;render()});document.getElementById('saveForm').addEventListener('submit',()=>{document.getElementById('layout_json').value=JSON.stringify(items)});await drawPdf();render();
</script></body></html>