<?php
declare(strict_types=1);
require __DIR__ . '/app/bootstrap.php';
require_once __DIR__ . '/app/Badge.php';
Auth::requireLogin();
$pdo=Database::connection();ensure_member_soft_delete_schema($pdo);ensure_badge_schema($pdo);
$id=(int)($_GET['id']??0);$mode=(string)($_GET['mode']??'view');
try{$member=badge_member_data($pdo,$id);$template=badge_pick_template($pdo,$member);if(!$template)throw new RuntimeException('Er is nog geen actieve algemene of taggebonden lidkaart-template ingesteld.');$layout=badge_layout($template);}catch(Throwable $e){http_response_code(404);?><!doctype html><html lang="nl"><head><meta charset="utf-8"><title>Lidkaart</title><style>body{font-family:Arial,sans-serif;padding:30px}.err{background:#feecec;padding:16px;border-radius:10px}</style></head><body><div class="err"><strong>Lidkaart kan niet worden gemaakt.</strong><p><?=e($e->getMessage())?></p><a href="/badge-templates.php">Ga naar lidkaart templates</a></div></body></html><?php exit;}
$data=[
'full_name'=>$member['full_name'],'first_name'=>$member['first_name'],'last_name'=>$member['last_name'],'member_number'=>$member['member_number']??'','photo'=>$member['photo_path']??'','member_type'=>$member['member_type_label'],'status'=>$member['status_label'],'member_since'=>$member['member_since']??'','birth_date'=>$member['birth_date']??'','email'=>$member['email']??'','mobile'=>$member['mobile']??'','address'=>$member['address']??'','postal_city'=>$member['postal_city'],'weight_kg'=>($member['weight_kg']??'')!==''?((string)$member['weight_kg'].' kg'):'','tags'=>$member['tags'],'payment_status'=>$member['payment_status_label'],'free_flight_entitled'=>$member['free_flight_entitled_label'],'free_flight_date'=>$member['free_flight_date']??''
];
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lidkaart <?=e($member['full_name'])?></title><style>
*{box-sizing:border-box}body{font-family:Arial,sans-serif;margin:0;background:#e8ebef;color:#171717}.toolbar{display:flex;justify-content:center;gap:10px;padding:14px;flex-wrap:wrap}.btn{padding:10px 14px;border:0;border-radius:9px;background:#111;color:#fff;text-decoration:none;cursor:pointer;font-weight:700}.secondary{background:#fff;color:#111}.wrap{display:flex;justify-content:center;padding:18px}.badge{position:relative;width:86mm;height:54mm;background:#fff;overflow:hidden;box-shadow:0 8px 28px #0004}.badge #bg{position:absolute;inset:0;width:100%;height:100%}.field{position:absolute;display:flex;align-items:center;overflow:hidden;line-height:1.05;white-space:nowrap}.code{background:transparent;justify-content:center}.code canvas,.code svg{max-width:100%;max-height:100%}.photoField img{width:100%;height:100%;object-fit:cover;display:block}@page{size:86mm 54mm;margin:0}@media print{html,body{width:86mm;height:54mm;background:#fff}.toolbar{display:none}.wrap{padding:0}.badge{box-shadow:none;page-break-after:avoid}}
</style></head><body><div class="toolbar"><button class="btn" id="printBtn">Print lidkaart</button><button class="btn" id="downloadBtn">Download Badge PDF</button><a class="btn secondary" href="/member.php?id=<?=$id?>">← Lidfiche</a></div><div class="wrap"><div class="badge" id="badge"><canvas id="bg"></canvas></div></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js"></script><script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.6/dist/JsBarcode.all.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.2/jspdf.umd.min.js"></script><script type="module">
import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const pdfUrl=<?=json_encode($template['pdf_path'],JSON_UNESCAPED_SLASHES)?>,layout=<?=json_encode($layout,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,data=<?=json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,memberNumber=<?=json_encode((string)($member['member_number']??''))?>,mode=<?=json_encode($mode)?>;
const badge=document.getElementById('badge'),bg=document.getElementById('bg'),ctx=bg.getContext('2d');function fmtDate(v){if(!v)return '';const p=String(v).split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:v}function value(field){if(['member_since','birth_date','free_flight_date'].includes(field))return fmtDate(data[field]||'');return data[field]??''}
async function drawPdf(){const pdf=await pdfjsLib.getDocument(pdfUrl).promise;const page=await pdf.getPage(1);const base=page.getViewport({scale:1});const scale=1400/base.width;const vp=page.getViewport({scale});bg.width=1400;bg.height=Math.round(vp.height);await page.render({canvasContext:ctx,viewport:vp}).promise}
function renderFields(){badge.querySelectorAll('.field').forEach(n=>n.remove());for(const it of layout){const d=document.createElement('div');d.className='field'+((it.field||'').includes('qr_')||(it.field||'').includes('barcode_')?' code':'')+(it.field==='photo'?' photoField':'');Object.assign(d.style,{left:(it.x/86*100)+'%',top:(it.y/54*100)+'%',width:(it.w/86*100)+'%',height:(it.h/54*100)+'%',fontFamily:it.font||'Arial',fontSize:(it.size||12)+'pt',color:it.color||'#111111',fontWeight:it.bold?'700':'400',justifyContent:it.align==='center'?'center':it.align==='right'?'flex-end':'flex-start',textAlign:it.align||'left'});if(it.field==='qr_member_number'){const q=document.createElement('div');d.appendChild(q);new QRCode(q,{text:memberNumber,width:300,height:300,correctLevel:QRCode.CorrectLevel.M});}else if(it.field==='barcode_member_number'){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');d.appendChild(svg);JsBarcode(svg,memberNumber,{format:'CODE128',displayValue:false,margin:0,height:80,width:2});}else if(it.field==='photo'){if(data.photo){const img=document.createElement('img');img.src=data.photo;d.appendChild(img)}}else d.textContent=value(it.field);badge.appendChild(d)}}
async function ready(){await drawPdf();renderFields();await new Promise(r=>setTimeout(r,350));if(mode==='print'){setTimeout(()=>window.print(),250)}if(mode==='download'){setTimeout(downloadPdf,350)}}
async function downloadPdf(){const canvas=await html2canvas(badge,{scale:4,useCORS:true,backgroundColor:'#ffffff'});const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'landscape',unit:'mm',format:[86,54],compress:true});pdf.addImage(canvas.toDataURL('image/png'),'PNG',0,0,86,54,undefined,'FAST');pdf.save('lidkaart-'+memberNumber+'.pdf')}
document.getElementById('printBtn').addEventListener('click',()=>window.print());document.getElementById('downloadBtn').addEventListener('click',downloadPdf);await ready();
</script></body></html>