<?php
declare(strict_types=1);
require __DIR__ . '/app/bootstrap.php';
Auth::requireLogin();

$pdo = Database::connection();
$memberCount = (int)$pdo->query('SELECT COUNT(*) FROM members')->fetchColumn();
$activeCount = (int)$pdo->query("SELECT COUNT(*) FROM members WHERE status = 'active'")->fetchColumn();
$flyingCount = (int)$pdo->query("SELECT COUNT(*) FROM members WHERE member_type = 'flying'")->fetchColumn();
$tagCount = (int)$pdo->query('SELECT COUNT(*) FROM tags')->fetchColumn();
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Heli One Members</title><style>body{font-family:Arial,sans-serif;background:#f5f6f8;margin:0;color:#171717}header{background:#111;color:#fff;padding:18px 28px;display:flex;justify-content:space-between;align-items:center}main{max-width:1180px;margin:36px auto;padding:0 22px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.card{background:#fff;border-radius:14px;padding:22px;box-shadow:0 4px 18px #0000000d}.value{font-size:34px;font-weight:800;margin-top:8px}.muted{color:#69707a}.actions{margin-top:28px;display:flex;gap:12px;flex-wrap:wrap}.btn{display:inline-block;padding:11px 16px;border-radius:9px;background:#111;color:#fff;text-decoration:none}.disabled{background:#dfe3e8;color:#6b7280}@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.grid{grid-template-columns:1fr}}</style></head><body><header><strong>Heli One Members</strong><div><?=e((string)($_SESSION['admin_name'] ?? 'Administrator'))?> · <a href="/logout.php" style="color:#fff">Afmelden</a></div></header><main><h1>Dashboard</h1><p class="muted">Beheeromgeving voor de Heli One leden.</p><section class="grid"><div class="card"><div class="muted">Totaal leden</div><div class="value"><?=$memberCount?></div></div><div class="card"><div class="muted">Actieve leden</div><div class="value"><?=$activeCount?></div></div><div class="card"><div class="muted">Vliegende leden</div><div class="value"><?=$flyingCount?></div></div><div class="card"><div class="muted">Tags</div><div class="value"><?=$tagCount?></div></div></section><div class="actions"><a class="btn" href="/members.php">Ledenbeheer</a><span class="btn disabled">Excel import — volgende stap</span><span class="btn disabled">Tags & batchacties — volgende stap</span></div></main></body></html>